import {
  Star,
  Heart,
  Zap,
  Trophy,
  Gift,
  Crown,
  Flame,
  Target,
  Rocket,
  Sparkles,
  Music,
  Camera,
  Coffee,
  Pizza,
  Gamepad2,
  Plane,
  Car,
  Bike,
  Home,
  Briefcase,
  Book,
  Lightbulb,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  PartyPopper,
  Bomb,
  Skull,
  Ghost,
  Bug,
} from 'lucide-react';

// Map of icon names to Lucide components
export const AVAILABLE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  star: Star,
  heart: Heart,
  zap: Zap,
  trophy: Trophy,
  gift: Gift,
  crown: Crown,
  flame: Flame,
  target: Target,
  rocket: Rocket,
  sparkles: Sparkles,
  music: Music,
  camera: Camera,
  coffee: Coffee,
  pizza: Pizza,
  gamepad: Gamepad2,
  plane: Plane,
  car: Car,
  bike: Bike,
  home: Home,
  briefcase: Briefcase,
  book: Book,
  lightbulb: Lightbulb,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  party: PartyPopper,
  bomb: Bomb,
  skull: Skull,
  ghost: Ghost,
  bug: Bug,
};
